# Generated by Django 3.2 on 2021-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20211130_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_product_name', models.CharField(max_length=1000)),
                ('transaction_product_price', models.CharField(max_length=100)),
                ('transaction_product_quantity', models.CharField(max_length=100)),
                ('transaction_totalamount', models.FloatField()),
            ],
        ),
    ]
