# Generated by Django 3.2 on 2021-12-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_product_name',
            new_name='transaction_products_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_product_price',
            new_name='transaction_products_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_product_quantity',
            new_name='transaction_products_quantity',
        ),
    ]
