# Generated by Django 3.2 on 2021-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20211202_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
