# Generated by Django 3.2 on 2021-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.IntegerField(null=True),
        ),
    ]
