# Generated by Django 3.2 on 2021-12-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_product_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_code',
        ),
    ]
