# Generated by Django 3.2 on 2021-12-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_product_reorder_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
