# Generated by Django 3.2 on 2021-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
