# Generated by Django 3.2 on 2021-12-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
